/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Controlador.DtoConfiguracion;
import Controlador.Singleton;
import java.awt.Dimension;
import java.awt.Toolkit;
import modelo.CasilleroMensajes;
import modelo.ColaMensajes;
import modelo.ColaProcesos;
import modelo.ConfiguracionSistema;
import modelo.Direccionamiento;
import modelo.Formato;
import modelo.ListaSolicitudes;
import modelo.ManejoColas;
import modelo.Sincronizacion;

/**
 *
 * @author curso
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        setSize(width/2, height/2);

        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_title = new javax.swing.JLabel();
        jTabbedPane_tabs = new javax.swing.JTabbedPane();
        javax.swing.JPanel jPanel_formato = new javax.swing.JPanel();
        jComboBox_format = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_typeContent = new javax.swing.JComboBox<>();
        jTextField_sizeOfMessage = new javax.swing.JTextField();
        jLabel_size = new javax.swing.JLabel();
        jPanel_disciplinaManejoColas = new javax.swing.JPanel();
        jComboBox_manejoDeColas = new javax.swing.JComboBox<>();
        jPanel_synchronization = new javax.swing.JPanel();
        jLabel_syncSend = new javax.swing.JLabel();
        jlabel_syncReceive = new javax.swing.JLabel();
        jComboBox_sendParameters = new javax.swing.JComboBox<>();
        jComboBox_receiveParameters = new javax.swing.JComboBox<>();
        jPanel_direccionamiento = new javax.swing.JPanel();
        jComboBox_adressingType = new javax.swing.JComboBox<>();
        jComboBox_addresingSubType = new javax.swing.JComboBox<>();
        jLabel_dirSend = new javax.swing.JLabel();
        jPanel_general = new javax.swing.JPanel();
        jLabel_numberOfProcesses = new javax.swing.JLabel();
        jTextField_numberOfProcesses = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_sizeOfQueue = new javax.swing.JTextField();
        jButton_guardarSettings = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField_mailboxSize = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        label_title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        label_title.setText("Configuración del Sistema");

        jTabbedPane_tabs.setToolTipText("sdgsd");

        jComboBox_format.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_format.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Largo Fijo", "Largo Variable" }));
        jComboBox_format.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_formatItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Largo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Contenido:");

        jComboBox_typeContent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_typeContent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Texto", "Video", "Audio", "Imagen" }));

        jLabel_size.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_size.setText("Tamaño:");

        javax.swing.GroupLayout jPanel_formatoLayout = new javax.swing.GroupLayout(jPanel_formato);
        jPanel_formato.setLayout(jPanel_formatoLayout);
        jPanel_formatoLayout.setHorizontalGroup(
            jPanel_formatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_formatoLayout.createSequentialGroup()
                .addGroup(jPanel_formatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_formatoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jComboBox_typeContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(276, 276, 276)
                        .addComponent(jComboBox_format, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_formatoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addGap(267, 267, 267)
                        .addComponent(jLabel2))
                    .addGroup(jPanel_formatoLayout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(jLabel_size)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_sizeOfMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel_formatoLayout.setVerticalGroup(
            jPanel_formatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_formatoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel_formatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel_formatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_format, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_typeContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_formatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_sizeOfMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_size))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jTabbedPane_tabs.addTab("Formato", jPanel_formato);

        jComboBox_manejoDeColas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_manejoDeColas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO", "Prioridad" }));

        javax.swing.GroupLayout jPanel_disciplinaManejoColasLayout = new javax.swing.GroupLayout(jPanel_disciplinaManejoColas);
        jPanel_disciplinaManejoColas.setLayout(jPanel_disciplinaManejoColasLayout);
        jPanel_disciplinaManejoColasLayout.setHorizontalGroup(
            jPanel_disciplinaManejoColasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_disciplinaManejoColasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jComboBox_manejoDeColas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(561, Short.MAX_VALUE))
        );
        jPanel_disciplinaManejoColasLayout.setVerticalGroup(
            jPanel_disciplinaManejoColasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_disciplinaManejoColasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox_manejoDeColas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(393, Short.MAX_VALUE))
        );

        jTabbedPane_tabs.addTab("Disciplinas de Manejo de Colas", jPanel_disciplinaManejoColas);

        jLabel_syncSend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_syncSend.setText("Send:");

        jlabel_syncReceive.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlabel_syncReceive.setText("Receive:");

        jComboBox_sendParameters.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_sendParameters.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blocking", "Nonblocking" }));

        jComboBox_receiveParameters.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_receiveParameters.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blocking", "NonBlocking", "Prueba de Llegada" }));

        javax.swing.GroupLayout jPanel_synchronizationLayout = new javax.swing.GroupLayout(jPanel_synchronization);
        jPanel_synchronization.setLayout(jPanel_synchronizationLayout);
        jPanel_synchronizationLayout.setHorizontalGroup(
            jPanel_synchronizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_synchronizationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_synchronizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_syncSend)
                    .addComponent(jComboBox_sendParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(146, 146, 146)
                .addGroup(jPanel_synchronizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_receiveParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_syncReceive, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel_synchronizationLayout.setVerticalGroup(
            jPanel_synchronizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_synchronizationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_synchronizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_syncSend)
                    .addComponent(jlabel_syncReceive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_synchronizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_sendParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_receiveParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(365, Short.MAX_VALUE))
        );

        jTabbedPane_tabs.addTab("Sincronización", jPanel_synchronization);

        jComboBox_adressingType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_adressingType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Directo", "Indirecto" }));
        jComboBox_adressingType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_adressingTypeItemStateChanged(evt);
            }
        });

        jComboBox_addresingSubType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_addresingSubType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Receive Explícito", "Receive Implícito" }));

        jLabel_dirSend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_dirSend.setText("Send");

        javax.swing.GroupLayout jPanel_direccionamientoLayout = new javax.swing.GroupLayout(jPanel_direccionamiento);
        jPanel_direccionamiento.setLayout(jPanel_direccionamientoLayout);
        jPanel_direccionamientoLayout.setHorizontalGroup(
            jPanel_direccionamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_direccionamientoLayout.createSequentialGroup()
                .addGroup(jPanel_direccionamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_direccionamientoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jComboBox_adressingType, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_direccionamientoLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel_direccionamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_dirSend)
                            .addComponent(jComboBox_addresingSubType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(461, Short.MAX_VALUE))
        );
        jPanel_direccionamientoLayout.setVerticalGroup(
            jPanel_direccionamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_direccionamientoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jComboBox_adressingType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox_addresingSubType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel_dirSend)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        jTabbedPane_tabs.addTab("Direccionamiento", jPanel_direccionamiento);

        jLabel_numberOfProcesses.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_numberOfProcesses.setText("Número de Procesos:");
        jLabel_numberOfProcesses.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("<html>Tamaño de la<br/>Cola de Mensajes:</html>");

        jTextField_sizeOfQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_sizeOfQueueActionPerformed(evt);
            }
        });

        jButton_guardarSettings.setText("Aceptar");
        jButton_guardarSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarSettingsActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tamaño de MailBox:");

        javax.swing.GroupLayout jPanel_generalLayout = new javax.swing.GroupLayout(jPanel_general);
        jPanel_general.setLayout(jPanel_generalLayout);
        jPanel_generalLayout.setHorizontalGroup(
            jPanel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_generalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_guardarSettings)
                .addGap(28, 28, 28))
            .addGroup(jPanel_generalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_generalLayout.createSequentialGroup()
                        .addComponent(jLabel_numberOfProcesses)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_numberOfProcesses, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_generalLayout.createSequentialGroup()
                        .addGroup(jPanel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_sizeOfQueue, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(jTextField_mailboxSize))))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        jPanel_generalLayout.setVerticalGroup(
            jPanel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_generalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_numberOfProcesses)
                    .addComponent(jTextField_numberOfProcesses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_sizeOfQueue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_mailboxSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                .addComponent(jButton_guardarSettings)
                .addGap(21, 21, 21))
        );

        jTabbedPane_tabs.addTab("General", jPanel_general);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTabbedPane_tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_title))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_title, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane_tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_adressingTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_adressingTypeItemStateChanged
        // TODO add your handling code here:

        String addresingParameter = (String)this.jComboBox_adressingType.getSelectedItem();
        //System.out.println(addresingParameter);

        if (addresingParameter.equals("Directo")){

            this.jComboBox_addresingSubType.removeAllItems();
            this.jLabel_dirSend.setVisible(true);
            this.jComboBox_addresingSubType.addItem("Receive Explícito");
            this.jComboBox_addresingSubType.addItem("Receive Implícito");


        }
        else{

            this.jComboBox_addresingSubType.removeAllItems();
            this.jComboBox_addresingSubType.addItem("Estático");
            this.jComboBox_addresingSubType.addItem("Dinámico");
            this.jLabel_dirSend.setVisible(false);

        }

    }//GEN-LAST:event_jComboBox_adressingTypeItemStateChanged

    private void jTextField_sizeOfQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_sizeOfQueueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_sizeOfQueueActionPerformed

    private void jComboBox_formatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_formatItemStateChanged
        // TODO add your handling code here:
        String addresingParameter = (String)this.jComboBox_format.getSelectedItem();
        System.out.println(addresingParameter);
        if(addresingParameter.equals("Largo Variable")){
            this.jLabel_size.setVisible(false);
            this.jTextField_sizeOfMessage.setVisible(false);
        }else{
            this.jLabel_size.setVisible(true);
            this.jTextField_sizeOfMessage.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox_formatItemStateChanged

    private void jButton_guardarSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarSettingsActionPerformed
        // TODO add your handling code here:

        // Datos de interfaz
        String tipoContenido = (String)this.jComboBox_typeContent.getSelectedItem();
        String tipoLargo = (String)this.jComboBox_format.getSelectedItem();
        
        int largoMensajes;
        if(tipoLargo.equals("Largo Fijo")){
            String largoString = this.jTextField_sizeOfMessage.getText();
            largoMensajes = Integer.parseInt(largoString);
        }
        else{
             largoMensajes = -1;
        }
        
        String manejoColasString = (String)this.jComboBox_manejoDeColas.getSelectedItem();
        String syncSend = (String)this.jComboBox_sendParameters.getSelectedItem();
        String syncReceive = (String)this.jComboBox_receiveParameters.getSelectedItem();
        
        String addresingType = (String)this.jComboBox_adressingType.getSelectedItem();
        String addresingSubType = (String)this.jComboBox_addresingSubType.getSelectedItem();
        String cantidadProcesosString = this.jTextField_numberOfProcesses.getText();
        int cantidadProcesos = Integer.parseInt(cantidadProcesosString);  
        String addresing = addresingType + addresingSubType;
        
        String tamanoColaMensajesString = (String)this.jTextField_sizeOfQueue.getText();
        int tamanoColaMensajes = Integer.parseInt(tamanoColaMensajesString);
        
        //int cantidadProcesos = Integer.parseInt(cantidadProcesosString);

        // Instancia de objetos
        ManejoColas manejoColas = new ManejoColas(manejoColasString);
        Formato formato = new Formato(tipoContenido,tipoLargo,largoMensajes);
        
        // Direccionamiento
        Direccionamiento direccionamiento = new Direccionamiento(addresing);
        
        if(addresingType.equals("Directo")){
            direccionamiento.setDirect(true);
            
            if(addresingSubType.equals("Receive Explícito")){
                direccionamiento.setReceiveExplicit(true);
                direccionamiento.setReceiveImplicit(false);
            }
            else{
                direccionamiento.setReceiveExplicit(false);
                direccionamiento.setReceiveImplicit(true);
            }  
        }
        else{
            direccionamiento.setDirect(false);
            if(addresingSubType.equals("Estático")){
                direccionamiento.setIndirectStatic(true);
                direccionamiento.setIndirectDynamic(false);
            }
            else{           
                direccionamiento.setIndirectStatic(false);
                direccionamiento.setIndirectDynamic(true);
                
            }
                
        }
        
        //---------------------------------------------------------------------
        Sincronizacion sincronizacion = new Sincronizacion(syncSend,syncReceive);
        
        // Instancia Confuguracion
        ConfiguracionSistema configuracion = new ConfiguracionSistema(cantidadProcesos, tamanoColaMensajes, sincronizacion, direccionamiento, formato, manejoColas);
        System.out.println(configuracion.toString());
        // Configuracion
        Singleton.getInstance().getControlador().setConfiguracionSistema(configuracion);
        int tamanoColaProcesos = Singleton.getInstance().getControlador().getConfiguracionSistema().getNumeroProcesos();
        
        // Cola de Procesos
        ColaProcesos colaProcesos = new ColaProcesos(tamanoColaProcesos);
        Singleton.getInstance().getControlador().setColaProcesos(colaProcesos);
        
        // Cola de Mensajes
        ColaMensajes colaMensajes = new ColaMensajes(tamanoColaMensajes);
        Singleton.getInstance().getControlador().setColaMensajes(colaMensajes);
        
        System.out.println("Configuracion Lista");
        
        
        // Casillero de Mensajes int largoMaximo, String manejoCola, String tipoLargo){
        int tamanoMailBox = 0;
        String sts = this.jTextField_mailboxSize.getText();
        if(!sts.equals("")){
            tamanoMailBox = Integer.parseInt(sts);
        }
        CasilleroMensajes casilleroMensajes = new CasilleroMensajes(tamanoMailBox,manejoColasString,tipoLargo);
        Singleton.getInstance().getControlador().setCasilleroMensaje(casilleroMensajes);
        
        // Creacion de Procesos
        Singleton.getInstance().getControlador().crearProcesos();
        Singleton.getInstance().getControlador().getColaProcesos().ImprimirColaProcesos();
       
            
        //lista Solicitudes
        ListaSolicitudes listaSolicitudes = new ListaSolicitudes();
        Singleton.getInstance().getControlador().setListaSolicitudes(listaSolicitudes);
        
        //Cola mensajes procesados
        ColaMensajes colaMensajesProcesados = new ColaMensajes(-1);
        Singleton.getInstance().getControlador().setColaMensajesProcesados(colaMensajesProcesados);
        this.dispose();
    }//GEN-LAST:event_jButton_guardarSettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_guardarSettings;
    private javax.swing.JComboBox<String> jComboBox_addresingSubType;
    private javax.swing.JComboBox<String> jComboBox_adressingType;
    private javax.swing.JComboBox<String> jComboBox_format;
    private javax.swing.JComboBox<String> jComboBox_manejoDeColas;
    private javax.swing.JComboBox<String> jComboBox_receiveParameters;
    private javax.swing.JComboBox<String> jComboBox_sendParameters;
    private javax.swing.JComboBox<String> jComboBox_typeContent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_dirSend;
    private javax.swing.JLabel jLabel_numberOfProcesses;
    private javax.swing.JLabel jLabel_size;
    private javax.swing.JLabel jLabel_syncSend;
    private javax.swing.JPanel jPanel_direccionamiento;
    private javax.swing.JPanel jPanel_disciplinaManejoColas;
    private javax.swing.JPanel jPanel_general;
    private javax.swing.JPanel jPanel_synchronization;
    private javax.swing.JTabbedPane jTabbedPane_tabs;
    private javax.swing.JTextField jTextField_mailboxSize;
    private javax.swing.JTextField jTextField_numberOfProcesses;
    private javax.swing.JTextField jTextField_sizeOfMessage;
    private javax.swing.JTextField jTextField_sizeOfQueue;
    private javax.swing.JLabel jlabel_syncReceive;
    private javax.swing.JLabel label_title;
    // End of variables declaration//GEN-END:variables
}
